version: "3.8"

services:
  rng:
    #build: rng
    image: rng:25012024-v4
    networks:
      - worker-rng
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/"]
      interval: 5s
      timeout: 1s
      retries: 2
      start_period: 10s

  hasher:
    #build: hasher
    image: hasher:25012024-v4
    networks:
      - worker-hasher
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/"]
      interval: 5s
      timeout: 2s
      retries: 2
      start_period: 10s

  webui:
    #build: webui
    image: webui:25012024-v4
    ports:
    - "8000:8080"
    volumes:
     - type: bind
       source: ./webui/files/
       target: /usr/app/files/
       read_only: true
    networks:
      - webui-redis
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/json"]
      interval: 5s
      timeout: 2s
      retries: 2
      start_period: 10s


  redis:
    image: redis:7.2.4
    networks:
      - worker-redis
      - webui-redis
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 2
      start_period: 15s

  worker:
    #build: worker
    image: worker:25012024-v4
    networks:
      - worker-rng
      - worker-hasher
      - worker-redis
    healthcheck:
      test: ["CMD", "netstat", "-an", "|", "grep", ":6379", "|", "grep", "ESTABLISHED"]
      interval: 5s
      timeout: 2s
      retries: 2
      start_period: 10s
      


networks:
  worker-rng:
  worker-hasher:
  worker-redis:
  webui-redis:
